"""Ajout du champ is_admin dans la table user

Revision ID: 50583d0c433e
Revises: 
Create Date: 2026-06-13 00:18:15.040438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50583d0c433e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
